### ISSUE TITLE
Conv_block

### ISSUE THREAD

**Issue by ARRARIAKU2** [erikycd/Heart_segmentation#2]
hi bro, can i ask something again?

im still confused with function def conv_block(input_tensor, num_filters), 
what is the use of this function? because I see in the next cell there is no syntax that calls the function

thank you

**Comment by erikycd** [comment]
Hi again,

You've noticed right. We initially implemented that function in the case of creating the U-Net from scratch. Since we used the pre-trained weights from ResNet50v2, that encoding function is no needed. The next step is to decode through the function defined as:

`def decoder_block(input_tensor, concat_tensor, num_filters):`

Let me know if is working as expected. Regards,
